import { db } from "@workspace/db";
import { academiesTable } from "@workspace/db/schema";
import { eq, sql } from "drizzle-orm";

const ACADEMY_SEED_DATA = [
  { key: "arsenal",            accessCode: "COACH-ARS-003", name: "Arsenal",                     logoText: "AFC",   primaryColor: "#EF0107", secondaryColor: "#FFFFFF", welcomeMessage: "Victoria Concordia Crescit. Welcome to the Arsenal Academy family.",                              maxStaffAccounts: 8, crestUrl: "/images/clubs/arsenal.svg" },
  { key: "aston-villa",         accessCode: "COACH-AST-009", name: "Aston Villa",                 logoText: "AVFC",  primaryColor: "#670E36", secondaryColor: "#95BFE5", welcomeMessage: "In Preparation is Victory. Your Villa story starts here.",                                         maxStaffAccounts: 8, crestUrl: "/images/clubs/aston-villa.svg" },
  { key: "bournemouth",         accessCode: "COACH-BOU-010", name: "Bournemouth",                 logoText: "AFCB",  primaryColor: "#DA291C", secondaryColor: "#000000", welcomeMessage: "Welcome to the Cherries Academy. Your journey on the south coast starts now.",                    maxStaffAccounts: 8, crestUrl: "/images/clubs/bournemouth.svg" },
  { key: "brentford",           accessCode: "COACH-BRE-011", name: "Brentford",                   logoText: "BFC",   primaryColor: "#E30613", secondaryColor: "#FFFFFF", welcomeMessage: "Welcome to Brentford Academy. Think differently, play boldly.",                                   maxStaffAccounts: 8, crestUrl: "/images/clubs/brentford.svg" },
  { key: "brighton",            accessCode: "COACH-BRI-012", name: "Brighton & Hove Albion",      logoText: "BHAFC", primaryColor: "#0057B8", secondaryColor: "#FFCD00", welcomeMessage: "Seagulls, your development journey begins at the Amex.",                                          maxStaffAccounts: 8, crestUrl: "/images/clubs/brighton.svg" },
  { key: "chelsea",             accessCode: "COACH-CHE-002", name: "Chelsea",                     logoText: "CFC",   primaryColor: "#034694", secondaryColor: "#DBA111", welcomeMessage: "Welcome to Cobham. Your blue journey starts here.",                                                maxStaffAccounts: 8, crestUrl: "/images/clubs/chelsea.svg" },
  { key: "crystal-palace",      accessCode: "COACH-CRY-013", name: "Crystal Palace",              logoText: "CPFC",  primaryColor: "#1B458F", secondaryColor: "#C4122E", welcomeMessage: "Glad All Over. Your Palace Academy story begins today.",                                           maxStaffAccounts: 8, crestUrl: "/images/clubs/crystal-palace.svg" },
  { key: "everton",             accessCode: "COACH-EVE-014", name: "Everton",                     logoText: "EFC",   primaryColor: "#003399", secondaryColor: "#FFFFFF", welcomeMessage: "Nil Satis Nisi Optimum — nothing but the best. Welcome to Everton Academy.",                     maxStaffAccounts: 8, crestUrl: "/images/clubs/everton.svg" },
  { key: "fulham",              accessCode: "COACH-FUL-015", name: "Fulham",                      logoText: "FFC",   primaryColor: "#CC0000", secondaryColor: "#FFFFFF", welcomeMessage: "Welcome to Fulham Academy. The Thames runs through our history.",                                 maxStaffAccounts: 8, crestUrl: "/images/clubs/fulham.svg" },
  { key: "ipswich",             accessCode: "COACH-IPS-016", name: "Ipswich Town",                logoText: "ITFC",  primaryColor: "#003781", secondaryColor: "#FFFFFF", welcomeMessage: "Welcome to Portman Road. Suffolk's finest, your story starts here.",                             maxStaffAccounts: 8, crestUrl: "/images/clubs/ipswich.svg" },
  { key: "leicester",           accessCode: "COACH-LEI-017", name: "Leicester City",              logoText: "LCFC",  primaryColor: "#003090", secondaryColor: "#FDBE11", welcomeMessage: "Welcome to the King Power. Your Foxes journey begins.",                                          maxStaffAccounts: 8, crestUrl: "/images/clubs/leicester.svg" },
  { key: "liverpool",           accessCode: "COACH-LIV-004", name: "Liverpool",                   logoText: "LFC",   primaryColor: "#C8102E", secondaryColor: "#F6EB61", welcomeMessage: "You'll Never Walk Alone. Begin your Anfield legacy.",                                             maxStaffAccounts: 8, crestUrl: "/images/clubs/liverpool.svg" },
  { key: "manchester-city",     accessCode: "COACH-MAN-005", name: "Manchester City",             logoText: "MCFC",  primaryColor: "#6CABDD", secondaryColor: "#1C2C5B", welcomeMessage: "Cityzens, your path to greatness starts at the City Football Academy.",                          maxStaffAccounts: 8, crestUrl: "/images/clubs/manchester-city.svg" },
  { key: "manchester-united",   accessCode: "COACH-MAN-006", name: "Manchester United",           logoText: "MUFC",  primaryColor: "#DA291C", secondaryColor: "#FBE122", welcomeMessage: "Welcome to Carrington. Build your United story.",                                                 maxStaffAccounts: 8, crestUrl: "/images/clubs/manchester-united.svg" },
  { key: "newcastle",           accessCode: "COACH-NEW-008", name: "Newcastle United",            logoText: "NUFC",  primaryColor: "#241F20", secondaryColor: "#FFFFFF", welcomeMessage: "Howay the Lads! Forge your path at the Newcastle Academy.",                                      maxStaffAccounts: 8, crestUrl: "/images/clubs/newcastle.svg" },
  { key: "nottingham-forest",   accessCode: "COACH-NOT-018", name: "Nottingham Forest",           logoText: "NFFC",  primaryColor: "#DD0000", secondaryColor: "#FFFFFF", welcomeMessage: "Welcome to the Garibaldi. Forest roots run deep — so will your story.",                         maxStaffAccounts: 8, crestUrl: "/images/clubs/nottingham-forest.svg" },
  { key: "southampton",         accessCode: "COACH-SOU-019", name: "Southampton",                 logoText: "SCFC",  primaryColor: "#D71920", secondaryColor: "#FFFFFF", welcomeMessage: "Welcome to Staplewood. The Saints Academy has shaped legends.",                                   maxStaffAccounts: 8, crestUrl: "/images/clubs/southampton.svg" },
  { key: "tottenham",           accessCode: "COACH-TOT-007", name: "Tottenham Hotspur",           logoText: "THFC",  primaryColor: "#132257", secondaryColor: "#FFFFFF", welcomeMessage: "To Dare Is To Do. Step into your Spurs future.",                                                  maxStaffAccounts: 8, crestUrl: "/images/clubs/tottenham.svg" },
  { key: "west-ham",            accessCode: "COACH-WES-020", name: "West Ham United",             logoText: "WHUFC", primaryColor: "#7A263A", secondaryColor: "#1BB1E7", welcomeMessage: "Forever Blowing Bubbles. Welcome to the West Ham Academy.",                                       maxStaffAccounts: 8, crestUrl: "/images/clubs/west-ham.svg" },
  { key: "wolves",              accessCode: "COACH-WOL-021", name: "Wolverhampton Wanderers",     logoText: "WWFC",  primaryColor: "#FDB913", secondaryColor: "#231F20", welcomeMessage: "Welcome to the Wolves Academy. Old Gold runs through everything we do.",                         maxStaffAccounts: 8, crestUrl: "/images/clubs/wolves.svg" },
  { key: "birmingham-city",     accessCode: "COACH-BIR-001", name: "Birmingham City",             logoText: "BCFC",  primaryColor: "#1B2D7E", secondaryColor: "#FFFFFF", welcomeMessage: "Keep Right On! Welcome to your Birmingham City development journey.",                            maxStaffAccounts: 8, crestUrl: "/images/clubs/birmingham-city.svg" },
  { key: "leeds",               accessCode: "COACH-LEE-022", name: "Leeds United",                logoText: "LUFC",  primaryColor: "#1D428A", secondaryColor: "#FFCD00", welcomeMessage: "Marching On Together. Leeds Academy — ambition without limits.",                                   maxStaffAccounts: 8, crestUrl: "/images/clubs/leeds.svg" },
  { key: "sunderland",          accessCode: "COACH-SUN-023", name: "Sunderland",                  logoText: "SAFC",  primaryColor: "#EB172B", secondaryColor: "#FFFFFF", welcomeMessage: "Ha'way the Lads! Sunderland Academy — built on pride and graft.",                                maxStaffAccounts: 8, crestUrl: "/images/clubs/sunderland.svg" },
  { key: "sheffield-united",    accessCode: "COACH-SHE-024", name: "Sheffield United",            logoText: "SUFC",  primaryColor: "#EE2737", secondaryColor: "#FFFFFF", welcomeMessage: "United as One. Sheffield United Academy starts your Blades journey.",                             maxStaffAccounts: 8, crestUrl: "/images/clubs/sheffield-united.svg" },
  { key: "west-brom",           accessCode: "COACH-WES-025", name: "West Bromwich Albion",        logoText: "WBA",   primaryColor: "#122F67", secondaryColor: "#FFFFFF", welcomeMessage: "Throstle pride runs deep. West Brom Academy — your story, your chapter.",                        maxStaffAccounts: 8, crestUrl: "/images/clubs/west-brom.svg" },
  { key: "middlesbrough",       accessCode: "COACH-MID-026", name: "Middlesbrough",               logoText: "MFC",   primaryColor: "#EE2020", secondaryColor: "#FFFFFF", welcomeMessage: "Boro born and Boro bred. The Riverside Academy is your launchpad.",                             maxStaffAccounts: 8, crestUrl: "/images/clubs/middlesbrough.svg" },
  { key: "burnley",             accessCode: "COACH-BUR-027", name: "Burnley",                     logoText: "BFC",   primaryColor: "#6C1D45", secondaryColor: "#99D6EA", welcomeMessage: "Clarets together. Burnley Academy — roots in the community, eyes on the top.",                   maxStaffAccounts: 8, crestUrl: "/images/clubs/burnley.svg" },
  { key: "norwich",             accessCode: "COACH-NOR-028", name: "Norwich City",                logoText: "NCFC",  primaryColor: "#00A650", secondaryColor: "#FFF200", welcomeMessage: "On the Ball City! Norwich Academy — the Canary in you is ready to fly.",                         maxStaffAccounts: 8, crestUrl: "/images/clubs/norwich.svg" },
  { key: "watford",             accessCode: "COACH-WAT-029", name: "Watford",                     logoText: "WFC",   primaryColor: "#FBEE23", secondaryColor: "#ED2127", welcomeMessage: "Come On You 'Orns! Watford Academy — building the future of the Hornets.",                        maxStaffAccounts: 8, crestUrl: "/images/clubs/watford.svg" },
  { key: "coventry",            accessCode: "COACH-COV-030", name: "Coventry City",               logoText: "CCFC",  primaryColor: "#59CBE8", secondaryColor: "#FFFFFF", welcomeMessage: "Sky Blue Army! Coventry Academy — your journey in sky blue.",                                   maxStaffAccounts: 8, crestUrl: "/images/clubs/coventry.svg" },
  { key: "sheffield-wednesday", accessCode: "COACH-SHE-031", name: "Sheffield Wednesday",         logoText: "SWFC",  primaryColor: "#0066B3", secondaryColor: "#FFFFFF", welcomeMessage: "Owls forever. Sheffield Wednesday Academy — wise players, bold futures.",                        maxStaffAccounts: 8, crestUrl: "/images/clubs/sheffield-wednesday.svg" },
  { key: "blackburn",           accessCode: "COACH-BLA-032", name: "Blackburn Rovers",            logoText: "BRFC",  primaryColor: "#009EE0", secondaryColor: "#FFFFFF", welcomeMessage: "Rovers forever. Blackburn Academy — blue and white, through and through.",                      maxStaffAccounts: 8, crestUrl: "/images/clubs/blackburn.svg" },
  { key: "stoke",               accessCode: "COACH-STO-033", name: "Stoke City",                  logoText: "SCFC",  primaryColor: "#E03A3E", secondaryColor: "#FFFFFF", welcomeMessage: "Delilah! Stoke City Academy — Potteries grit, Premier League ambition.",                       maxStaffAccounts: 8, crestUrl: "/images/clubs/stoke.svg" },
  { key: "hull",                accessCode: "COACH-HUL-034", name: "Hull City",                   logoText: "HCAFC", primaryColor: "#F5A12D", secondaryColor: "#231F20", welcomeMessage: "Tigers together. Hull City Academy — amber and black, building your story.",                     maxStaffAccounts: 8, crestUrl: "/images/clubs/hull.svg" },
  { key: "cardiff",             accessCode: "COACH-CAR-035", name: "Cardiff City",                logoText: "CCFC",  primaryColor: "#0070B5", secondaryColor: "#FFFFFF", welcomeMessage: "Bluebirds rising. Cardiff Academy — your story in the Welsh capital.",                          maxStaffAccounts: 8, crestUrl: "/images/clubs/cardiff.svg" },
  { key: "derby",               accessCode: "COACH-DER-036", name: "Derby County",                logoText: "DCFC",  primaryColor: "#FFFFFF",  secondaryColor: "#241F21", welcomeMessage: "Pride of the Midlands. Derby Academy — your Ram story begins.",                                maxStaffAccounts: 8, crestUrl: "/images/clubs/derby.svg" },
  { key: "millwall",            accessCode: "COACH-MIL-037", name: "Millwall",                    logoText: "MFC",   primaryColor: "#001D5E", secondaryColor: "#FFFFFF", welcomeMessage: "No One Likes Us, We Don't Care. Millwall Academy — lion-hearted players.",                     maxStaffAccounts: 8, crestUrl: "/images/clubs/millwall.svg" },
  { key: "luton",               accessCode: "COACH-LUT-038", name: "Luton Town",                  logoText: "LTFC",  primaryColor: "#F78F1E", secondaryColor: "#001F5B", welcomeMessage: "Come On You Hatters! Luton Academy — keep on keeping on.",                                       maxStaffAccounts: 8, crestUrl: "/images/clubs/luton.svg" },
  { key: "qpr",                 accessCode: "COACH-QPR-039", name: "Queens Park Rangers",         logoText: "QPR",   primaryColor: "#1D5BA4", secondaryColor: "#FFFFFF", welcomeMessage: "QPR Academy — Hoops ambition, no limits.",                                                        maxStaffAccounts: 8, crestUrl: "/images/clubs/qpr.svg" },
  { key: "bristol-city",        accessCode: "COACH-BRI-040", name: "Bristol City",                logoText: "BCFC",  primaryColor: "#E00000", secondaryColor: "#FFFFFF", welcomeMessage: "Seize The Day. Bristol City Academy — the city's red heart beats for you.",                    maxStaffAccounts: 8, crestUrl: "/images/clubs/bristol-city.svg" },
  { key: "swansea",             accessCode: "COACH-SWA-041", name: "Swansea City",                logoText: "SCAFC", primaryColor: "#121212", secondaryColor: "#FFFFFF", welcomeMessage: "Swans together. Swansea City Academy — your Welsh journey on the Liberty.",                     maxStaffAccounts: 8, crestUrl: "/images/clubs/swansea.svg" },
  { key: "portsmouth",          accessCode: "COACH-POR-042", name: "Portsmouth",                  logoText: "PFC",   primaryColor: "#001489", secondaryColor: "#FFFFFF", welcomeMessage: "Play Up Pompey! Portsmouth Academy — Fratton spirit in every step.",                             maxStaffAccounts: 8, crestUrl: "/images/clubs/portsmouth.svg" },
];

export async function seedAcademies() {
  try {
    for (const academy of ACADEMY_SEED_DATA) {
      const existing = await db
        .select({ id: academiesTable.id })
        .from(academiesTable)
        .where(eq(academiesTable.key, academy.key))
        .limit(1);

      if (existing.length === 0) {
        await db.insert(academiesTable).values(academy);
        console.log(`[seed] Inserted academy: ${academy.name}`);
      } else {
        // Patch access_code and crestUrl on pre-existing records if missing
        await db.execute(
          sql`UPDATE academies SET access_code = ${academy.accessCode} WHERE key = ${academy.key} AND access_code IS NULL`
        );
        if (academy.crestUrl) {
          await db.execute(
            sql`UPDATE academies SET crest_url = ${academy.crestUrl} WHERE key = ${academy.key} AND crest_url IS NULL`
          );
        }
      }
    }
    console.log(`[seed] Academies seeded (${ACADEMY_SEED_DATA.length} total)`);
  } catch (err) {
    console.error("[seed] Failed to seed academies:", err);
  }
}
